apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowtime.fullname" . }}-client
  labels:
    {{- include "flowtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "flowtime.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "flowtime.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
          imagePullPolicy: {{ .Values.image.client.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe.client | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.client | nindent 12 }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowtime.fullname" . }}-client
  labels:
    {{- include "flowtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flowtime.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
