apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowtime.fullname" . }}-server
  labels:
    {{- include "flowtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "flowtime.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "flowtime.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe.server | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.server | nindent 12 }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "flowtime.fullname" . }}-server-config
            - secretRef:
                name: {{ include "flowtime.fullname" . }}-secrets
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
